### ISSUE TITLE
Crashes, tries to find "MIAJapaneseSupport"

### ISSUE THREAD

**Issue by honmashinsei** [Kodeama/-Anki-Shinmeikai-Addon#5]
Broken again, 

Not everyone is running the MIA support plugin :)

+ it's looking for "japanese", but in Anki 2.1 anki puts plugins into numbered folders, instead of using the name of the plugin. The number for the Japanese Support plugin is "3918629684"

**Comment by Kodeama** [comment]
You probably saw my respons I wrote for a few minutes ago that you have to change what the folder is called in the config.py file.
But I will go and set "3918629684" as the default because thats what most people have I'm assuming. So you can just download the newest version when its updated (should be in a minute or two)

**Comment by honmashinsei** [comment]
Nice work! It doesn't crash anymore and also the hiragana fix works. Thanks :)
